package fatec.br.projetormi.cliente.GUI;

import fatec.br.projetormi.servidor.DAO.Cadastro_clientesDAO;
import fatec.br.projetormi.servidor.ServidorInter;
import fatec.br.projetormi.servidor.conexao.Conexao;
import fatec.br.projetormi.servidor.VO.Cadastro_clientesVO;
import java.net.MalformedURLException;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author henrique
 */
public class Cadastro_clientesGUI extends javax.swing.JFrame {
    
    private String sexo;
    Conexao conexao = new Conexao();
    Cadastro_clientesDAO cadastro_clientesDAO = new Cadastro_clientesDAO(conexao);
    
    
    public void limparCampos(){

        rb_feminino.setSelected(false);
        rb_masculino.setSelected(false);
        txt_nome.setText("");
        txt_rg.setText("");
        txt_cpf.setText("");
        txt_datanasc.setText("");
        txt_endereco_cliente.setText("");
        txt_endereco_cliente_numero.setText("");
        txt_endereco_cliente_complemento.setText("");
        txt_endereco_cliente_cep.setText("");
        txt_endereco_cliente_cidade.setText("");
        txt_endereco_cliente_uf.setText("");
        txt_endereco_cliente_pais.setText("");
        txt_email_cliente.setText("");
        txt_celular_cliente.setText("");
        txt_telefone_cliente.setText("");
        ptxt_senha_cliente.setText("");
        
    }
    
    /**
     * Creates new form Cadastro
     */
    public Cadastro_clientesGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        bt_group = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        bt_voltar = new javax.swing.JButton();
        btPesquisar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_email_cliente = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        txt_celular_cliente = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_telefone_cliente = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        ptxt_senha_cliente = new javax.swing.JPasswordField();
        jPanel8 = new javax.swing.JPanel();
        txt_endereco_cliente_cep = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txt_endereco_cliente_numero = new javax.swing.JTextField();
        txt_endereco_cliente = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        txt_endereco_cliente_complemento = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        txt_endereco_cliente_cidade = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        txt_endereco_cliente_uf = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        txt_endereco_cliente_pais = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JFormattedTextField();
        txt_rg = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_datanasc = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        rb_feminino = new javax.swing.JRadioButton();
        rb_masculino = new javax.swing.JRadioButton();
        bt_excluir = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        bt_voltar.setText("Voltar");
        bt_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_voltarActionPerformed(evt);
            }
        });

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btLimpar.setText("Limpar Tudo");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel3.setText("Email");

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Telefones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        try {
            txt_celular_cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel12.setText("Cel.");

        jLabel15.setText("Tel.");

        try {
            txt_telefone_cliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_celular_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_telefone_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_celular_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txt_telefone_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Senha");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txt_email_cliente, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(ptxt_senha_cliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, 0)
                .addComponent(txt_email_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ptxt_senha_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Localização", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        txt_endereco_cliente_cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_cepActionPerformed(evt);
            }
        });

        jLabel36.setText("CEP");

        jLabel37.setText("Número");

        txt_endereco_cliente_numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_numeroActionPerformed(evt);
            }
        });

        jLabel14.setText("Endereço");

        jLabel38.setText("Complemento");

        txt_endereco_cliente_complemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_complementoActionPerformed(evt);
            }
        });

        jLabel39.setText("Cidade");

        txt_endereco_cliente_cidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_cidadeActionPerformed(evt);
            }
        });

        jLabel40.setText("UF");

        txt_endereco_cliente_uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_ufActionPerformed(evt);
            }
        });

        jLabel41.setText("País");

        txt_endereco_cliente_pais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_endereco_cliente_paisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_endereco_cliente_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_endereco_cliente_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_endereco_cliente_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_endereco_cliente_pais)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_endereco_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_endereco_cliente_numero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_endereco_cliente_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(5, 5, 5)
                        .addComponent(txt_endereco_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel38)
                            .addGap(26, 26, 26))
                        .addComponent(txt_endereco_cliente_complemento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel37)
                            .addGap(5, 5, 5)
                            .addComponent(txt_endereco_cliente_numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_endereco_cliente_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_endereco_cliente_cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_endereco_cliente_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel41)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_endereco_cliente_pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel16.setText("Nome completo");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        try {
            txt_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_cpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cpfFocusLost(evt);
            }
        });

        try {
            txt_rg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-A")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_rg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_rgFocusLost(evt);
            }
        });

        jLabel1.setText("RG");

        jLabel2.setText("CPF");

        jLabel7.setText("Data Nascimento");

        try {
            txt_datanasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sexo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        bt_group.add(rb_feminino);
        rb_feminino.setText("Feminino");
        rb_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_femininoActionPerformed(evt);
            }
        });

        bt_group.add(rb_masculino);
        rb_masculino.setText("Masculino");
        rb_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_masculinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(rb_masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_feminino))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rb_masculino)
                .addComponent(rb_feminino))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_nome)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(txt_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        bt_excluir.setText("Excluir");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_excluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void rb_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_femininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_femininoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        conexao.setNomeBanco("leilaoapp");
        conexao.setPorta(3306);
        conexao.setSenha("");
        conexao.setServidor("localhost");
        conexao.setUsuario("root");   
        btAlterar.setEnabled(false);
        bt_excluir.setEnabled(false);

    }//GEN-LAST:event_formWindowOpened

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        
        boolean valida;
        ServidorInter objeto1 = null;

        if (txt_telefone_cliente.getText().isEmpty()
                || txt_nome.getText().isEmpty()
                || txt_rg.getText().isEmpty()
                || txt_cpf.getText().isEmpty()
                || txt_datanasc.getText().isEmpty()
                || rb_masculino.getText().isEmpty()
                || rb_feminino.getText().isEmpty()
                || txt_endereco_cliente.getText().isEmpty()
                || txt_endereco_cliente_numero.getText().isEmpty()
                || txt_endereco_cliente_complemento.getText().isEmpty()
                || txt_endereco_cliente_cep.getText().isEmpty()
                || txt_endereco_cliente_cidade.getText().isEmpty()
                || txt_endereco_cliente_uf.getText().isEmpty()
                || txt_endereco_cliente_pais.getText().isEmpty()
                || txt_email_cliente.getText().isEmpty()
                || txt_celular_cliente.getText().isEmpty()
                || ptxt_senha_cliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite campos obrigatórios", "Formulário Incompleto", JOptionPane.WARNING_MESSAGE);
            return;
        }

        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();

        if (rb_masculino.isSelected()) {
            sexo = "M";
        }
        if (rb_feminino.isSelected()) {
            sexo = "F";
        }

        String strData = txt_datanasc.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        java.util.Date dataUtil = null;

        try {
            dataUtil = sdf.parse(strData);
        } catch (ParseException ex) {
            Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.sql.Date dataNascSql;
        dataNascSql = new java.sql.Date(dataUtil.getTime());

        //dados pessoais
        cadastro_clientesVO.setNome(txt_nome.getText());
        cadastro_clientesVO.setRg(txt_rg.getText());
        cadastro_clientesVO.setCpf(txt_cpf.getText());
        cadastro_clientesVO.setSexo(sexo);
        cadastro_clientesVO.setDatanasc(dataNascSql);
        //endereço
        cadastro_clientesVO.setEndereco_cliente(txt_endereco_cliente.getText());
        cadastro_clientesVO.setEndereco_cliente_numero(txt_endereco_cliente_numero.getText());
        cadastro_clientesVO.setEndereco_cliente_complemento(txt_endereco_cliente_complemento.getText());
        cadastro_clientesVO.setEndereco_cliente_cep(txt_endereco_cliente_cep.getText());
        cadastro_clientesVO.setEndereco_cliente_pais(txt_endereco_cliente_pais.getText());
        cadastro_clientesVO.setEndereco_cliente_uf(txt_endereco_cliente_uf.getText());
        cadastro_clientesVO.setEndereco_cliente_cidade(txt_endereco_cliente_cidade.getText());
        //contatos
        cadastro_clientesVO.setEmail_cliente(txt_email_cliente.getText());
        cadastro_clientesVO.setTelefone_cliente(txt_telefone_cliente.getText());
        cadastro_clientesVO.setCelular_cliente(txt_celular_cliente.getText());
        cadastro_clientesVO.setSenha_cliente(ptxt_senha_cliente.getText());

        try {
            LocateRegistry.getRegistry("192.168.0.102");
            objeto1 = (ServidorInter) Naming.lookup("rmi://localhost:9999/MensageiroService");
            valida = objeto1.cadastrarCli(cadastro_clientesVO);

            if (valida == true) {
                JOptionPane.showMessageDialog(rootPane, "Cadastro feito com sucesso",
                        "Mensagem ao Usuário", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                AutentificacaoGUI autentificacaoGUI = new AutentificacaoGUI();
                autentificacaoGUI.setVisible(true);
            }

        } catch (MalformedURLException | RemoteException | NotBoundException e) {
            // TODO Auto-generated catch block
            System.out.println("problema de conexão" + e);
        }
        

        /* 
          try {
            cadastro_clientesDAO.cadastrarCli(cadastro_clientesVO);
            JOptionPane.showMessageDialog(rootPane, "Cadastro feito com sucesso",
                        "Mensagem ao Usuário", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(Level.SEVERE, null, ex);
        } */
        limparCampos();

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void rb_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_masculinoActionPerformed

    }//GEN-LAST:event_rb_masculinoActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        if (txt_telefone_cliente.getText().isEmpty()
                || txt_nome.getText().isEmpty()
                || txt_rg.getText().isEmpty()
                || txt_cpf.getText().isEmpty()
                || txt_datanasc.getText().isEmpty()
                || rb_masculino.getText().isEmpty()
                || rb_feminino.getText().isEmpty()
                || txt_endereco_cliente.getText().isEmpty()
                || txt_endereco_cliente_numero.getText().isEmpty()
                || txt_endereco_cliente_complemento.getText().isEmpty()
                || txt_endereco_cliente_cep.getText().isEmpty()
                || txt_endereco_cliente_cidade.getText().isEmpty()
                || txt_endereco_cliente_uf.getText().isEmpty()
                || txt_endereco_cliente_pais.getText().isEmpty()
                || txt_email_cliente.getText().isEmpty()
                || txt_celular_cliente.getText().isEmpty()
                || ptxt_senha_cliente.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite campos obrigatórios", "Formulário Incompleto", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //cria um novo clienteVO
        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();
        //seta as informaçoes do clienteVO
        if (rb_masculino.isSelected()) {
            sexo = "M";
        }
        if (rb_feminino.isSelected()) {
            sexo = "F";
        }

        String strData = txt_datanasc.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        java.util.Date dataUtil = null;

        try {
            dataUtil = sdf.parse(strData);
        } catch (ParseException ex) {
            Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.sql.Date dataNascSql;
        dataNascSql = new java.sql.Date(dataUtil.getTime());

        //dados pessoais
        cadastro_clientesVO.setNome(txt_nome.getText());
        cadastro_clientesVO.setRg(txt_rg.getText());
        cadastro_clientesVO.setCpf(txt_cpf.getText());
        cadastro_clientesVO.setSexo(sexo);
        cadastro_clientesVO.setDatanasc(dataNascSql);
        //endereço
        cadastro_clientesVO.setEndereco_cliente(txt_endereco_cliente.getText());
        cadastro_clientesVO.setEndereco_cliente_numero(txt_endereco_cliente_numero.getText());
        cadastro_clientesVO.setEndereco_cliente_complemento(txt_endereco_cliente_complemento.getText());
        cadastro_clientesVO.setEndereco_cliente_cep(txt_endereco_cliente_cep.getText());
        cadastro_clientesVO.setEndereco_cliente_pais(txt_endereco_cliente_pais.getText());
        cadastro_clientesVO.setEndereco_cliente_uf(txt_endereco_cliente_uf.getText());
        cadastro_clientesVO.setEndereco_cliente_cidade(txt_endereco_cliente_cidade.getText());
        //contatos
        cadastro_clientesVO.setEmail_cliente(txt_email_cliente.getText());
        cadastro_clientesVO.setTelefone_cliente(txt_telefone_cliente.getText());
        cadastro_clientesVO.setCelular_cliente(txt_celular_cliente.getText());
        cadastro_clientesVO.setSenha_cliente(ptxt_senha_cliente.getText());

        try {
            if (cadastro_clientesDAO.editarCli(cadastro_clientesVO) == true) {
                JOptionPane.showMessageDialog(rootPane, "Alteração OK",
                        "Mensagem ao Usuário", JOptionPane.INFORMATION_MESSAGE);
                btAlterar.setEnabled(false);
                bt_excluir.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Erro na Alteração",
                        "Mensagem ao Usuário", JOptionPane.ERROR_MESSAGE);
                btAlterar.setEnabled(false);
                bt_excluir.setEnabled(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        limparCampos();

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        if (txt_cpf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o CPF para realizar a pesquisa", "Alerta", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        ServidorInter objeto1 = null;
        Cadastro_clientesVO cadastro_clientesVO = new Cadastro_clientesVO();
        //abastecer com a PK

        cadastro_clientesVO.setCpf(txt_cpf.getText());

        /* String CPF;
        CPF = txtCpf.getValue().toString();
        cadastro_clientesVO.setCpf(CPF);*/
        try {
            LocateRegistry.getRegistry("192.168.0.102");
            objeto1 = (ServidorInter) Naming.lookup("rmi://localhost:9999/MensageiroService");
            cadastro_clientesVO = objeto1.buscarCli(cadastro_clientesVO);

            if (cadastro_clientesVO == null) {
                JOptionPane.showMessageDialog(rootPane, "Dados nao encontrados!",
                        "Mensagem ao Usuário",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                //achou, entao jogar dados para tela

                txt_cpf.setText(cadastro_clientesVO.getCpf());
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

                String dateString;
                dateString = sdf.format(cadastro_clientesVO.getDatanasc());

                txt_nome.setText(cadastro_clientesVO.getNome());
                txt_rg.setText(cadastro_clientesVO.getRg());
                txt_cpf.setText(cadastro_clientesVO.getCpf());
                txt_datanasc.setText(dateString);

                txt_endereco_cliente.setText(cadastro_clientesVO.getEndereco_cliente());
                txt_endereco_cliente_numero.setText(cadastro_clientesVO.getEndereco_cliente_numero());
                txt_endereco_cliente_complemento.setText(cadastro_clientesVO.getEndereco_cliente_complemento());
                txt_endereco_cliente_cep.setText(cadastro_clientesVO.getEndereco_cliente_cep());
                txt_endereco_cliente_cidade.setText(cadastro_clientesVO.getEndereco_cliente_cidade());
                txt_endereco_cliente_uf.setText(cadastro_clientesVO.getEndereco_cliente_uf());
                txt_endereco_cliente_pais.setText(cadastro_clientesVO.getEndereco_cliente_pais());

                txt_email_cliente.setText(cadastro_clientesVO.getEmail_cliente());
                txt_celular_cliente.setText(cadastro_clientesVO.getCelular_cliente());
                txt_telefone_cliente.setText(cadastro_clientesVO.getTelefone_cliente());
                ptxt_senha_cliente.setText(cadastro_clientesVO.getSenha_cliente());

                if ("M".equals(cadastro_clientesVO.getSexo())) {
                    rb_masculino.setSelected(true);
                }
                if ("F".equals(cadastro_clientesVO.getSexo())) {
                    rb_feminino.setSelected(true);
                }

                btAlterar.setEnabled(true);
                bt_excluir.setEnabled(true);
                btCadastrar.setEnabled(false);
            }

        } catch (MalformedURLException | RemoteException | NotBoundException e) {
            // TODO Auto-generated catch block
            System.out.println("problema de conexão" + e);
        }
         
         
        /*
        try {
            //pesquisa no banco
            cadastro_clientesVO = cadastro_clientesDAO.buscarCli(cadastro_clientesVO);
            if(cadastro_clientesVO == null) {
                JOptionPane.showMessageDialog(rootPane, "Dados nao encontrados!",
                    "Mensagem ao Usuário", 
                    JOptionPane.INFORMATION_MESSAGE);
            } else {
                //achou, entao jogar dados para tela
                
                
                txt_cpf.setText(cadastro_clientesVO.getCpf());
                SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
                
                String dateString;
                dateString = sdf.format(cadastro_clientesVO.getDatanasc());
                
                txt_nome.setText(cadastro_clientesVO.getNome());
                txt_rg.setText(cadastro_clientesVO.getRg());
                txt_cpf.setText(cadastro_clientesVO.getCpf());
                txt_datanasc.setText(dateString);


                txt_endereco_cliente.setText(cadastro_clientesVO.getEndereco_cliente());
                txt_endereco_cliente_numero.setText(cadastro_clientesVO.getEndereco_cliente_numero());
                txt_endereco_cliente_complemento.setText(cadastro_clientesVO.getEndereco_cliente_complemento());
                txt_endereco_cliente_cep.setText(cadastro_clientesVO.getEndereco_cliente_cep());
                txt_endereco_cliente_cidade.setText(cadastro_clientesVO.getEndereco_cliente_cidade());
                txt_endereco_cliente_uf.setText(cadastro_clientesVO.getEndereco_cliente_uf());
                txt_endereco_cliente_pais.setText(cadastro_clientesVO.getEndereco_cliente_pais());

                txt_email_cliente.setText(cadastro_clientesVO.getEmail_cliente());
                txt_celular_cliente.setText(cadastro_clientesVO.getCelular_cliente());
                txt_telefone_cliente.setText(cadastro_clientesVO.getTelefone_cliente());
                ptxt_senha_cliente.setText(cadastro_clientesVO.getSenha_cliente());
                
                if("M".equals(cadastro_clientesVO.getSexo()))
                    rb_masculino.setSelected(true);
                if("F".equals(cadastro_clientesVO.getSexo()))
                    rb_feminino.setSelected(true);
                
            btAlterar.setEnabled(true);
            bt_excluir.setEnabled(true);
            btCadastrar.setEnabled(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro no try " + 
                    ex.getMessage(), "Mensagem ao Usuário", 
                    JOptionPane.ERROR_MESSAGE);
        }*/
        
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void txt_rgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_rgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rgFocusLost

    private void txt_cpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cpfFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cpfFocusLost

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//new Menu_principal().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void txt_endereco_cliente_cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_cepActionPerformed

    private void txt_endereco_cliente_numeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_numeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_numeroActionPerformed

    private void txt_endereco_cliente_complementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_complementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_complementoActionPerformed

    private void txt_endereco_cliente_cidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_cidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_cidadeActionPerformed

    private void txt_endereco_cliente_ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_ufActionPerformed

    private void txt_endereco_cliente_paisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_endereco_cliente_paisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_endereco_cliente_paisActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
     /**
     * Este metodo chama o objeto gerenciarClientesDAO para remocao de cliente no banco
     */    
        String cpf = txt_cpf.getText(); //Armazena o cpf digitado em txtCpf
        String nome = txt_nome.getText(); //Armazena nome digitado em txtNome
        
        ServidorInter objeto1 = null;
        
        
        try {
            LocateRegistry.getRegistry("192.168.0.102");
            objeto1 = (ServidorInter) Naming.lookup("rmi://localhost:9999/MensageiroService");
            objeto1.deletarCli(cpf);

        } catch (MalformedURLException | RemoteException | NotBoundException e) {
            // TODO Auto-generated catch block
            System.out.println("problema de conexão" + e);
        }
            JOptionPane.showMessageDialog(null, "Cliente " + nome + " excluido com sucesso!"); //Prompt de mensagem 
            limparCampos(); //Execulta o metodo para limpar os campos
            this.dispose();
            AutentificacaoGUI autentificacaoGUI = new AutentificacaoGUI();
                autentificacaoGUI.setVisible(true);
            
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_voltarActionPerformed
        AutentificacaoGUI autentificacaoGUI = new AutentificacaoGUI(); //Cria o objeto menu
        autentificacaoGUI.setVisible(true); //Exibe objeot menu
        this.dispose(); //Fecha o form GerenciarClientes
        
        
    }//GEN-LAST:event_bt_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_clientesGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_clientesGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.ButtonGroup bt_group;
    private javax.swing.JButton bt_voltar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField ptxt_senha_cliente;
    private javax.swing.JRadioButton rb_feminino;
    private javax.swing.JRadioButton rb_masculino;
    private javax.swing.JFormattedTextField txt_celular_cliente;
    private javax.swing.JFormattedTextField txt_cpf;
    private javax.swing.JFormattedTextField txt_datanasc;
    private javax.swing.JTextField txt_email_cliente;
    private javax.swing.JTextField txt_endereco_cliente;
    private javax.swing.JTextField txt_endereco_cliente_cep;
    private javax.swing.JTextField txt_endereco_cliente_cidade;
    private javax.swing.JTextField txt_endereco_cliente_complemento;
    private javax.swing.JTextField txt_endereco_cliente_numero;
    private javax.swing.JTextField txt_endereco_cliente_pais;
    private javax.swing.JTextField txt_endereco_cliente_uf;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JFormattedTextField txt_rg;
    private javax.swing.JFormattedTextField txt_telefone_cliente;
    // End of variables declaration//GEN-END:variables
}
